server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/heretic604/config
      label: main

#spring:
#  profiles:
#    include: native
#  application.name: config
#  cloud.config.server:
#    native.search-locations: classpath:client-config/, classpath:client-config/{application}