server:
  port: 8888

spring:
  profiles:
    include: native
  application.name: config
  cloud.config.server:
    native.search-locations: classpath:config/, classpath:config/{application}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    preferIpAddress: true